name: Test App
permissions: read-all
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Docker Image
    outputs:
      success: ${{ steps.test-image.outputs.success }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Docker Image
        id: test-image
        uses: outoforbitdev/action-docker-test@v0.0.2
        with:
          test-command: sh ./tests.sh
