name: Test App
permissions: read-all
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
    branches:
      - main
      - beta
      - dev
      - staging
jobs:
  testimage:
    runs-on: ubuntu-latest
    name: Test Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Docker Image
        uses: outoforbitdev/action-docker-test@v1.0.0-staging.1
        with:
          test-command: sh ./tests.sh
      - name: Test Release
        uses: outoforbitdev/action-semantic-release@v1.4.1
        id: semanticrelease
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
      - name: Test Docker Publish
        uses: outoforbitdev/action-docker-publish@v1.2.0-staging.8
        id: dockerpublish
        with:
          docker-username: ${{ vars.DOCKER_USERNAME }}
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          image-name: ${{ vars.IMAGE_NAME }}
          image-tag: 'exampletag'
          dry-run: true
      - name: Latest version
        run: echo "Latest version is ${{ steps.semanticrelease.outputs.version}}"
